name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag qywx-push:$(date +%s)
      
    - name: Test the Docker image
      run: |
        docker run --rm -d --name test-container -p 12121:12121 qywx-push:$(date +%s)
        sleep 5
        docker stop test-container
